version: 0.0
os: linux
files:
  - source: /
    destination: /opt/aws/nodeApp/node-server/

hooks:  
  BeforeInstall:
    - location: script/installdependencies.sh
      timeout: 300
      runas: root  
  ApplicationStart:
    - location: script/startnodeapp.sh
      timeout: 300
      runas: root    
    
    
