version: 0.0
os: linux
files:
  - source: /
    destination: /opt/aws/nodeApp/

hooks:  
  AfterInstall:
    - location: script/startserver.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: script/startnodeapp.sh
      timeout: 300
      runas: root    
    
    
