version: 0.0
os: linux
files:
  - source: /
    destination: /opt/aws/nodeApp/

hooks:
  
  AfterInstall:
    - location: node server.js
      timeout: 3600
    - location: startserver.sh
      timeout: 3600
