version: 0.0
os: linux
files:
  - source: /server.js
    destination: /opt/aws/nodeApp/

hooks:  
  AfterInstall:
    - location: startserver.sh
      timeout: 3600
      runas:root
    - location: node server.js
      timeout: 3600
      runas:root
