version: 0.0
os: linux
files:
  - source: /
    destination: /opt/aws/nodeApp/

hooks:  
  AfterInstall:
    - location: script/startserver.sh
      timeout: 300
      runas: root  
  ValidateService:
    - location: script/validate.sh
      timeout: 100
      runas: root
   
    
    
